name: Build and Deploy
on:
  workflow_dispatch:
    inputs:
      region:
        description: 'aws region'
        type: string
        required: false
env:
  duplo_host: https://liquibit-dev.duplocloud.net  # CHANGE ME!
  duplo_token: "${{ secrets.LIQUIBIT_DEV_DUPLO_TOKEN }}"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # Upload to S3
      - name: Get AWS credentials
        uses: duplocloud/ghactions-aws-jit@fff9f31df51b300f69fb740b041ea6bec74c6b4a
        with:
           admin: true
           aws_region: ${{ inputs.region }}
       # How to sync an entire folder
      - name: Test EC2 list
        run: aws ec2 describe-instances
        env:
          REGION: ${{ inputs.region }}