name: Build-And-Deploy-Slack
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    branches:
      - 'develop'
  push:
    branches:
      - develop

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: "Deployment of <Repository>"
          author_name: "Subhash"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.APP0_SLACK_WEBHOOK }}
        if: always()
