name: Build-Feature
on:
  workflow_dispatch:
  push:
    branches:
      - "feature/*"
      - "bug/*"

env:
  allowed_users: "${{secrets.PROD_DEPLOYMENT_APPOVERS}}"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: Development
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: 3.8
      - name: Install dependencies
        run: |
            python3 -m pip install --upgrade pip
            pip3 install pycodestyle
      - name: python linting
        run: |
            pycodestyle . --exclude=venv,.aws-sam --max-line-length=200 > pycodestyle_output.txt && echo -e "\033[32mLint Checking Passed\033[0m"
            if [ -s pycodestyle_output.txt ]; then
                echo "Pycodestyle errors found:"
                cat pycodestyle_output.txt
                exit 1
            fi
      - name: python unit tests
        run: |
            python test_calculator.py
      - name: actor name
        run: |
            echo "${GITHUB_ACTOR}"
            for author_name in ${{vars.PROD_DEPLOYMENT_APPOVERS_ENV}}
            do
              if [[ "${GITHUB_ACTOR}" == *"$author_name"* ]]; then
                echo "User $author is Authorized."
                break
              else
                printf '%s\n' "User ${author_name} is not allowed to run this workflow."
                exit 1
              fi
            done
      - uses: actions/checkout@master
        with:
          repository: duplocloud/docs
          path: ./docs
          submodules: recursive
      - name: list files
        run: |
            ls -ltr
            ls -ltr docs/
          
        

