name: Build-And-Deploy-Develop
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    branches:
      - 'develop'
  push:
    branches:
      - development

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: Development
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: 3.8
      - name: Install dependencies
        run: |
            python3 -m pip install --upgrade pip
            pip3 install pycodestyle
      - name: python linting
        run: |
            pycodestyle . --exclude=venv,.aws-sam --max-line-length=200 > pycodestyle_output.txt && echo -e "\033[32mLint Checking Passed\033[0m"
            if [ -s pycodestyle_output.txt ]; then
                echo "Pycodestyle errors found:"
                cat pycodestyle_output.txt
                exit 1
            fi
      - name: python unit tests
        run: |
            python test_calculator.py
      - name: Get AWS credentials
        run: |
          echo "Getting AWS credentials"
      - name: Login to Amazon ECR
        run: |
          echo "Log in to Amazon ECR"
      - name: Docker Build and Push
        run: |
          echo "Building Image and Pushing image to ECR"
  deploy:
    needs:
      - build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DuploCloud
        run: |
          echo "Deploying Image to duplocloud"
      - name: Integration testing
        run: |
            echo "Integration Testing"

  notify:
    needs:
      - deploy
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: Ilshidur/action-slack@master
        with:
          status: ${{ job.status }}
          environment: production
          branch: ${{ github.ref }}
          deployed_by: ${{ github.actor }}
          slack_webhook_url: "https://hooks.slack.com/services/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"
