name: Build-And-Deploy-Slack
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    branches:
      - 'develop'
  push:
    branches:
      - develop

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.APP0_SLACK_WEBHOOK }}
