name: Build-And-Deploy-Dev
on:
    workflow_dispatch:
    push:
        branches:
        - akshay-test
env:
    ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: Development
    defaults:
      run:
        shell: bash
    steps:
        - name: getPrUrl
          id: pr-url
          uses: ammaratef45/pr-url-action@v1
        - name: display
          run: echo ${{ steps.pr-url.outputs.url }}
        - name: Get Pull Request URL
          run: |
            PR_URL=${{ github.event.pull_request.number }}
            echo "Pull Request URL: $PR_URL"
        - uses: actions/github-script@v6
          id: get_issue_number
          with:
            script: |
                if (context.issue.number) {
                // Return issue number if present
                return context.issue.number;
                } else {
                // Otherwise return issue number from commit
                return (
                    await github.rest.repos.listPullRequestsAssociatedWithCommit({
                    commit_sha: context.sha,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    })
                ).data[0].number;
                }
            result-encoding: string
        - name: Issue number
          run: echo '${{steps.get_issue_number.outputs.result}}'
        - name: Get PR Author
          run: |
            PR_NUMBER=${{steps.get_issue_number.outputs.result}}
            GITHUB_TOKEN=${{ secrets.PA_TOKEN }}
            API_URL="https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}"
  
            AUTHOR=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" $API_URL | jq -r '.user.login')
  
            echo "PR Author: $AUTHOR"    
        - name: test
        run: |
            echo: "HI"
        # - name: Test
        #   uses: actions/github-script@0.3.0
        #   with:
        #     github-token: ${{ secrets.PA_TOKEN }}"
        #     script: |
        #         const core = require('@actions/core')
        #         const prNumber = context.payload.number;
        #         core.exportVariable('PULL_NUMBER', prNumber);
        
# Imp links:
# https://stackoverflow.com/questions/46340474/set-a-default-reviewer
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
# https://dennessphillip.medium.com/default-reviewers-for-pull-requests-7e68ae1a0ed9

# for pull request details
# https://stackoverflow.com/questions/59077079/how-to-get-pull-request-number-within-github-actions-workflow