name: Build-And-Deploy-Dev
on:
  pull_request:
    types:
        - opened

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: Development
    defaults:
      run:
        shell: bash
    steps:
        - name: Get Pull Request URL
          run: |
            PR_URL=${{ github.event.pull_request.number }}
            echo "Pull Request URL: $PR_URL"