name: Build-And-Deploy-Dev
on:
  workflow_dispatch:
  push:
    branches:
      - akshay-test

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: Development
    defaults:
      run:
        shell: bash
    steps:
        - name: Get Pull Request URL
          run: |
            PR_URL=${{ github.event.pull_request.html_url }}
            echo "Pull Request URL: $PR_URL"