name: SXF Migration on AWS

on: 
  pull_request:
    types:
    - opened
    - closed
    - synchronize

env:
  duplo_host: https://techstyle.duplocloud.net  
  duplo_token: "${{ secrets.DUPLO_TOKEN }}"

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: |
          bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
    - name: Clone!
      run: git clone git@bitbucket.org:techstyleinc/duplocloud-poc-iac.git
    - name: check
      run: ls -lrt duplocloud-poc-iac
    - name: check2
      run: ls -lrt

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.11

    - name: Set env vars for PR open
      if: github.event.action == 'opened' || github.event.action == 'synchronize'
      run: |
        echo "Base_Branch=$(echo $GITHUB_HEAD_REF | tr '/' '-')" >> $GITHUB_ENV

    # Update the scheduled tasks to use the new image
    - name: Deploy
      run: |
        set -euo pipefail
        cd duplocloud-poc-iac
        scripts/apply.sh "${{ env.Base_Branch }}" savagex \
          -var ecs_service_name="p-${{ github.event.number }}"
      env:
        AWS_RUNNER: duplo-admin